---
# 2019-11-21.08:33 - mark
# safhir-id-deploy
# playbook/server/server_app_az_cli.yml
#
# install azure cli

- name: install az cli tools to server
  hosts: "{{ variable_host| default('tag_function_BaseInstance:tag_workflow_JustCreated') }}"
  remote_user: "{{ remote_user_account }}"
  vars:
    ansible_ssh_pipelining: no
    env: "{{ vpc_env }}"
    # Options - lower case: staging | prod
    azone: "az1"
    # Options: az1 | az2 | az3
    sub_zone: "app"
    role_type: "{{ role_type| default('vmi') }}"
    # Options: vmi | smh | smh_app

    sg_zone: "{{ vpc_env }}-{{ role_type }}-APP"
    env_az: "{{ vpc_env }}-{{ azone }}"
    #    env_cf_data_version: "20"
    #    env_cf_app_version: "01"
    build_subnet_id: null
  vars_files:
    - "./../../vault/{{ cloud_client }}/{{ vpc_env }}/{{ role_type }}/vault.yml"
    - "./../../vars/{{ cloud_client }}/{{ vpc_env }}/{{ role_type }}/env.yml"
    - "./../../vault/{{ cloud_client }}/{{ vpc_env }}/vault.yml"
    - "./../../vars/{{ cloud_client }}/{{ vpc_env }}/env.yml"
    - "./../../vars/{{ cloud_client }}/common.yml"

  roles:

